services:
    # Form Loader
    l91_sulu_website_user.form_type.loader:
        class: L91\Sulu\Bundle\WebsiteUserBundle\Loader\FormTypeLoader

    # Mail Helper
    l91_sulu_website_user.mail_helper:
        class: L91\Sulu\Bundle\WebsiteUserBundle\Mail\MailHelper
        arguments: [@mailer]

    # Registration Handler
    l91_sulu_website_user.registration.handler:
        class: L91\Sulu\Bundle\WebsiteUserBundle\Form\RegistrationHandler
        arguments: [@sulu_security.salt_generator, @security.encoder_factory, @doctrine.orm.entity_manager]

    # Confirmation Handler
    l91_sulu_website_user.confirmation.handler:
        class: L91\Sulu\Bundle\WebsiteUserBundle\Form\ConfirmationHandler
        arguments: [@doctrine.orm.entity_manager]

