Sulu\Bundle\SecurityBundle\Entity\BaseUser:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: username
            groups: [registration, profile]
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: email
            groups: [registration, profile]
    properties:
        username:
            - NotBlank: { groups: [registration, profile] }
        email:
            - Email: { groups: [registration, profile] }

Sulu\Bundle\SecurityBundle\Entity\ContactInterface:
    properties:
        first_name:
            - NotBlank: { groups: [registration, profile] }
        last_name:
            - NotBlank: { groups: [registration, profile] }

Sulu\Bundle\SecurityBundle\Entity\Address:
    properties:
        country:
            - NotBlank: { groups: [registration, profile] }
